#include <stdio.h>
#include "object.h"
#include "toggle.h"
static const char* tags0[] = { "bathroom", NULL };
static const char* tags1[] = { "west", "north", "south", "forest", "east", NULL };
static const char* tags2[] = { "north", NULL };
static const char* tags3[] = { "washroom", "toilet", NULL };
static const char* tags4[] = { "shower", "bath", NULL };
static const char* tags5[] = { "toothbrush", "tooth brush", "brush", NULL };
static const char* tags6[] = { "bedroom", NULL };
static const char* tags7[] = { "south", "door", "doorway", NULL };
static const char* tags8[] = { "south", "door", "doorway", NULL };
static const char* tags9[] = { "east","west", NULL };
static const char* tags10[] = { "north","exit", NULL };
static const char* tags11[] = { "backpack", "bag", "backpack", NULL };
static const char* tags12[] = { "keychain", "keys", "key set", NULL };
static const char* tags13[] = { "road", NULL };
static const char* tags14[] = { "west","north","south", NULL };
static const char* tags15[] = { "south", "door", "doorway", NULL };
static const char* tags16[] = { "south", "door", "doorway", NULL };
static const char* tags17[] = { "south", "door", "doorway", NULL };
static const char* tags18[] = { "library", NULL };
static const char* tags19[] = { "exit","west", NULL };
static const char* tags20[] = { "reception", NULL };
static const char* tags21[] = { "east", NULL };
static const char* tags22[] = { "book shelf","shelves","shelf", NULL };
static const char* tags23[] = { "book shelf 1","shelf 1", NULL };
static const char* tags24[] = { "book shelf 2","shelf 2", NULL };
static const char* tags25[] = { "book shelf 3","shelf 3", NULL };
static const char* tags26[] = { "book shelf 4","shelf 4", NULL };
static const char* tags27[] = { "exit", NULL };
static const char* tags28[] = { "exit", NULL };
static const char* tags29[] = { "exit", NULL };
static const char* tags30[] = { "exit", NULL };
static const char* tags31[] = { "toilet", NULL };
static const char* tags32[] = { "toilet", NULL };
static const char* tags33[] = { "toilet", NULL };
static const char* tags34[] = { "toilet", NULL };
static const char* tags35[] = { "toilet", NULL };
static const char* tags36[] = { "east", NULL };
static const char* tags37[] = { "wash basin","sink","south", NULL };
static const char* tags38[] = { "urinal","urinals", NULL };
static const char* tags39[] = { "supply closet","closet", NULL };
static const char* tags40[] = { "urinal cabin 1","cabin 1", NULL };
static const char* tags41[] = { "urinal cabin 2","cabin 2", NULL };
static const char* tags42[] = { "urinal cabin 3","cabin 3","north", NULL };
static const char* tags43[] = { "urinal cabin 3","cabin 3", NULL };
static const char* tags44[] = { "urinal cabin 4","cabin 4", NULL };
static const char* tags45[] = { "exit","toilet exit", NULL };
static const char* tags46[] = { "body","mysterious body","guard", NULL };
static const char* tags47[] = { "portal", NULL };
static const char* tags48[] = { "portal","north", NULL };
static const char* tags49[] = { "toilet","east", NULL };
static const char* tags50[] = { "wash basin","sink", NULL };
static const char* tags51[] = { "urinal","urinals", NULL };
static const char* tags52[] = { "supply closet","closet", NULL };
static const char* tags53[] = { "urinal cabin 1","cabin 1", NULL };
static const char* tags54[] = { "urinal cabin 2","cabin 2", NULL };
static const char* tags55[] = { "urinal cabin 3","cabin 3", NULL };
static const char* tags56[] = { "urinal cabin 4","cabin 4", NULL };
static const char* tags57[] = { "exit","toilet exit", NULL };
static const char* tags58[] = { "book shelf","shelves","shelf", NULL };
static const char* tags59[] = { "book shelf 1","shelf 1", NULL };
static const char* tags60[] = { "book shelf 2","shelf 2", NULL };
static const char* tags61[] = { "book shelf 3","shelf 3", NULL };
static const char* tags62[] = { "book shelf 4","shelf 4", NULL };
static const char* tags63[] = { "exit", NULL };
static const char* tags64[] = { "exit", NULL };
static const char* tags65[] = { "exit", NULL };
static const char* tags66[] = { "exit", NULL };
static const char* tags67[] = { "toilet", NULL };
static const char* tags68[] = { "toilet", NULL };
static const char* tags69[] = { "toilet", NULL };
static const char* tags70[] = { "toilet", NULL };
static const char* tags71[] = { "toilet", NULL };
static const char* tags72[] = { NULL };
static const char* tags73[] = { "Exit", NULL };
static const char* tags74[] = { NULL };
static const char* tags75[] = { "apartment", NULL };
static const char* tags76[] = { "card", NULL };
static const char* tags77[] = { "inside", NULL };
static const char* tags78[] = { "outside","exit","back", NULL };
static const char* tags79[] = { "up", NULL };
static const char* tags80[] = { "upstairs", NULL };
static const char* tags81[] = { "downstairs","down","back", NULL };
static const char* tags82[] = { "hall", NULL };
static const char* tags83[] = { "living hall","hall", NULL };
static const char* tags84[] = { "upstairs","back", NULL };
static const char* tags85[] = { "bedroom", NULL };
static const char* tags86[] = { "bedroom", NULL };
static const char* tags87[] = { "living hall","hall","back", NULL };
static const char* tags88[] = { "table", NULL };
static const char* tags89[] = { "experiment table", NULL };
static const char* tags90[] = { "living hall","hall","back", NULL };
static const char* tags91[] = { "dinner table", NULL };
static const char* tags92[] = { "dining table", NULL };
static const char* tags93[] = { "living hall","hall","back", NULL };
static const char* tags94[] = { "wash basin","sink", NULL };
static const char* tags95[] = { "urinal","urinals", NULL };
static const char* tags96[] = { "supply closet","closet", NULL };
static const char* tags97[] = { "urinal cabin 1","cabin 1", NULL };
static const char* tags98[] = { "urinal cabin 2","cabin 2", NULL };
static const char* tags99[] = { "urinal cabin 3","cabin 3", NULL };
static const char* tags100[] = { "urinal cabin 4","cabin 4", NULL };
static const char* tags101[] = { "exit","toilet exit", NULL };
static const char* tags102[] = { "library", NULL };
static const char* tags103[] = { "exit","west", NULL };
static const char* tags104[] = { "reception", NULL };
static const char* tags105[] = { "east", NULL };
static const char* tags106[] = { "west","hall", NULL };
static const char* tags107[] = { "stairs","up", NULL };
static const char* tags108[] = { "down","stairs", NULL };
static const char* tags109[] = { "second floor", NULL };
static const char* tags110[] = { "shelf","east", NULL };
static const char* tags111[] = { "book shelf 1","shelf 1", NULL };
static const char* tags112[] = { "book shelf 2","shelf 2", NULL };
static const char* tags113[] = { "book shelf 3","shelf 3", NULL };
static const char* tags114[] = { "book shelf 4","shelf 4", NULL };
static const char* tags115[] = { "hall","west", NULL };
static const char* tags116[] = { "exit","west", NULL };
static const char* tags117[] = { "exit","west", NULL };
static const char* tags118[] = { "exit","west", NULL };
static const char* tags119[] = { "exit","west", NULL };
static const char* tags120[] = { "computer","computer corner", NULL };
static const char* tags121[] = { "book", NULL };
static const char* tags122[] = { "lakshagriha", NULL };
static const char* tags123[] = { "entrance", NULL };
static const char* tags124[] = { "lakshagrihacastle", NULL };
static const char* tags125[] = { "north","lakshagrihacastle", NULL };
static const char* tags126[] = { "east","west", NULL };
static const char* tags127[] = { "south","exit", NULL };
static const char* tags128[] = { "road", NULL };
static const char* tags129[] = { "road", NULL };
static const char* tags130[] = { "west","east","north", NULL };
static const char* tags131[] = { "exit", NULL };
static const char* tags132[] = { "village", NULL };
static const char* tags133[] = { "entrance","south", NULL };
static const char* tags134[] = { "west","east", NULL };
static const char* tags135[] = { "exit", NULL };
static const char* tags136[] = { "road", NULL };
static const char* tags137[] = { "north", NULL };
static const char* tags138[] = { "west","east", NULL };
static const char* tags139[] = { "exit", NULL };
static const char* tags140[] = { "hastinapurcastle", NULL };
static const char* tags141[] = { "east", NULL };
static const char* tags142[] = { "north", NULL };
static const char* tags143[] = { "meetinghall", NULL };
static const char* tags144[] = { "south", NULL };
static const char* tags145[] = { "exit", NULL };
static const char* tags146[] = { "second floor", NULL };
static const char* tags147[] = { "shelf","east", NULL };
static const char* tags148[] = { "book shelf 1","shelf 1", NULL };
static const char* tags149[] = { "book shelf 2","shelf 2", NULL };
static const char* tags150[] = { "book shelf 3","shelf 3", NULL };
static const char* tags151[] = { "book shelf 4","shelf 4", NULL };
static const char* tags152[] = { "hall","west", NULL };
static const char* tags153[] = { "exit","west", NULL };
static const char* tags154[] = { "exit","west", NULL };
static const char* tags155[] = { "exit","west", NULL };
static const char* tags156[] = { "exit","west", NULL };
static const char* tags157[] = { "stairs","up", NULL };
static const char* tags158[] = { "stairs","up", NULL };
static const char* tags159[] = { "stairs","up", NULL };
static const char* tags160[] = { "stairs","up", NULL };
static const char* tags161[] = { "stairs","up", NULL };
static const char* tags162[] = { "third floor", NULL };
static const char* tags163[] = { "down","east","second floor", NULL };
static const char* tags164[] = { "table 1","west", NULL };
static const char* tags165[] = { "table 2","north", NULL };
static const char* tags166[] = { "table 2","south", NULL };
static const char* tags167[] = { "book", NULL };
static const char* tags168[] = { "surrounding", NULL };
static const char* tags169[] = { "east", NULL };
static const char* tags170[] = { "guard", "burly guard", NULL };
static const char* tags171[] = { "yourself", NULL };

static bool alwaysTrue(void) { return true; }

OBJECT objs[] = {
	{	/* 0 = bathroom */
		0,
		alwaysTrue,
		 "a smelly bathroom",
		"That is something that can not be used\n",
		tags0,
		NULL,
		NULL,
		NULL,
		 "The bathroom is crampped and has just the essentials",
		"You see",
		 "You entred the bathroom\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		 99999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 1 = bathroomWallToilet */
		0,
		alwaysTrue,
		 "bathroom wall",
		"That is something that can not be used\n",
		tags1,
		 bathroom,
		NULL,
		NULL,
		 "The field is surrounded by trees and undergrowth.\n",
		"You see",
		 "Dense forest is blocking the way.\n",
		 "You cannot go there, it is impenetrable.",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 2 = bedroomEntrance */
		0,
		alwaysTrue,
		 "Entrance of the bedroom",
		"That is something that can not be used\n",
		tags2,
		 bathroom,
		 bedroom,
		 bedroom,
		"You see nothing special.\n",
		"You see",
		 "You entred the bedroom\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 3 = toilet */
		 1,
		alwaysTrue,
		 "a toilet with a bidet",
		"That is something that can not be used\n",
		tags3,
		 bathroom,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 4 = shower */
		0,
		alwaysTrue,
		 "a shower",
		"That is something that can not be used\n",
		tags4,
		 bathroom,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 5 = toothbrush */
		0,
		alwaysTrue,
		 "a chewed out toothbrush",
		"That is something that can not be used\n",
		tags5,
		 bathroom,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 6 = bedroom */
		0,
		alwaysTrue,
		 "Your bedroom",
		"That is something that can not be used\n",
		tags6,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You entred the bedroom\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 7 = openDoorToBackroom */
		0,
		alwaysTrue,
		 "an open door to the bathroom",
		"That is something that can not be used\n",
		tags7,
		NULL,
		 bathroom,
		 bathroom,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into a backroom.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		 isAlreadyOpen,
		 toggleBackdoor,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 8 = closedDoorToBackroom */
		0,
		alwaysTrue,
		 "a closed door to the bathroom",
		"That is something that can not be used\n",
		tags8,
		 bedroom,
		NULL,
		 bathroom,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		 toggleBackdoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 9 = bedroomWalls */
		0,
		alwaysTrue,
		 "Your bedroom walls",
		"That is something that can not be used\n",
		tags9,
		 bedroom,
		NULL,
		 bedroomWalls,
		"You see nothing special.\n",
		"You see",
		 "There is nothing but walls there\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 10 = bedroomExit */
		0,
		alwaysTrue,
		 "Exit of the house",
		"That is something that can not be used\n",
		tags10,
		 bedroom,
		 roadLibrary,
		 roadLibrary,
		"You see nothing special.\n",
		"You see",
		 "You are on the road\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 11 = backpack */
		 2,
		alwaysTrue,
		 "a worn out backpack",
		"That is something that can not be used\n",
		tags11,
		 bedroom,
		NULL,
		NULL,
		 "The bag has many pockets to carry all your essentials",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 12 = libraryKeys */
		0,
		alwaysTrue,
		 "a set of keys with a sonic screwdriver keychain",
		"That is something that can not be used\n",
		tags12,
		 bedroom,
		NULL,
		NULL,
		 "The key is really small and shiny.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 1,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 13 = roadLibrary */
		0,
		alwaysTrue,
		 "the road to the library",
		"That is something that can not be used\n",
		tags13,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are on the road",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 14 = roadWalls */
		0,
		alwaysTrue,
		 "Some closed down shops",
		"That is something that can not be used\n",
		tags14,
		 roadLibrary,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "There is nothing but locked shops there\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 15 = openDoorToLibrary */
		0,
		alwaysTrue,
		 "an open door to the library",
		"That is something that can not be used\n",
		tags15,
		NULL,
		 library,
		 library,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into a backroom.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		 isAlreadyOpen,
		 toggleBackdoor,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 16 = closedDoorToLibrary */
		0,
		alwaysTrue,
		 "a closed door to the library",
		"That is something that can not be used\n",
		tags16,
		NULL,
		NULL,
		 library,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		 toggleBackdoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 17 = lockedDoorToLibrary */
		0,
		alwaysTrue,
		 "a closed door to the library",
		"That is something that can not be used\n",
		tags17,
		 roadLibrary,
		NULL,
		 library,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		 toggleBackdoor,
		 isAlreadyClosed,
		 isAlreadyLocked,
		 toggleBoxLock
	},
	{	/* 18 = library */
		0,
		alwaysTrue,
		 "an old dusty library",
		"That is something that can not be used\n",
		tags18,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You have entred the library",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 19 = libraryExit */
		0,
		alwaysTrue,
		 "Exit of the library",
		"That is something that can not be used\n",
		tags19,
		 library,
		 roadLibrary,
		 roadLibrary,
		"You see nothing special.\n",
		"You see",
		 "You exited the library\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 20 = libraryReception */
		0,
		alwaysTrue,
		 "The library reception",
		"That is something that can not be used\n",
		tags20,
		NULL,
		NULL,
		NULL,
		 "This is the reception of the library. This is your station you spend all your days here.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 21 = libraryShelfEntrance */
		0,
		alwaysTrue,
		 "The section with the book shelves",
		"That is something that can not be used\n",
		tags21,
		 library,
		 libraryShelf,
		 libraryShelf,
		 "This is the reception of the library. This is your station you spend all your days here.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 22 = libraryShelf */
		0,
		alwaysTrue,
		 "The section with the book shelves",
		"That is something that can not be used\n",
		tags22,
		NULL,
		NULL,
		NULL,
		 "This is the reception of the library. This is your station you spend all your days here.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 23 = shelf_1 */
		0,
		alwaysTrue,
		 "Book Shelf Number 1\n",
		"That is something that can not be used\n",
		tags23,
		 libraryShelf,
		 shelf_1,
		 shelf_1,
		 "There are 2 books missing from this shelf.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 24 = shelf_2 */
		0,
		alwaysTrue,
		 "Book Shelf Number 2\n",
		"That is something that can not be used\n",
		tags24,
		 libraryShelf,
		 shelf_2,
		 shelf_2,
		 "There is 1 books missing from this shelf.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 25 = shelf_3 */
		0,
		alwaysTrue,
		 "Book Shelf Number 3\n",
		"That is something that can not be used\n",
		tags25,
		 libraryShelf,
		 shelf_3,
		 shelf_3,
		 "There are 2 books missing from this shelf.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 26 = shelf_4 */
		0,
		alwaysTrue,
		 "Book Shelf Number 4\n",
		"That is something that can not be used\n",
		tags26,
		 libraryShelf,
		 shelf_4,
		 shelf_4,
		 "There are 2 books missing from this shelf.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 27 = shelf_1_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags27,
		 shelf_1,
		 libraryShelf,
		 libraryShelf,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 28 = shelf_2_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags28,
		 shelf_2,
		 libraryShelf,
		 libraryShelf,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 29 = shelf_3_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags29,
		 shelf_3,
		 libraryShelf,
		 libraryShelf,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 30 = shelf_4_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags30,
		 shelf_4,
		 libraryShelf,
		 libraryShelf,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 31 = shelf_1_toilet */
		0,
		alwaysTrue,
		 "Entrance of the toilet",
		"That is something that can not be used\n",
		tags31,
		 shelf_1,
		 libraryToilet,
		 libraryToilet,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 32 = shelf_2_toilet */
		0,
		alwaysTrue,
		 "Entrance of the toilet",
		"That is something that can not be used\n",
		tags32,
		 shelf_2,
		 libraryToilet,
		 libraryToilet,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 33 = shelf_3_toilet */
		0,
		alwaysTrue,
		 "Entrance of the toilet",
		"That is something that can not be used\n",
		tags33,
		 shelf_3,
		 libraryToilet,
		 libraryToilet,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 34 = shelf_4_toilet */
		0,
		alwaysTrue,
		 "Entrance of the toilet",
		"That is something that can not be used\n",
		tags34,
		 shelf_4,
		 libraryToilet,
		 libraryToilet,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 35 = shelf_toilet */
		0,
		alwaysTrue,
		 "Entrance of the toilet",
		"That is something that can not be used\n",
		tags35,
		 libraryShelf,
		 libraryToilet,
		 libraryToilet,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 36 = libraryToilet */
		0,
		alwaysTrue,
		 "The library toilet",
		"That is something that can not be used\n",
		tags36,
		NULL,
		NULL,
		NULL,
		 "It's dirty and has some weird mass lying around urinal cabin 3. It is glowing with some wierd glow",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 37 = sink */
		0,
		alwaysTrue,
		 "Wash Basin",
		 "You have washed your hands and face",
		tags37,
		 libraryToilet,
		NULL,
		NULL,
		 "The tap in the wash basin is leaking slowly and there is no way to close it properly",
		"You see",
		 "You see the wash basin and the urinal on this side of the toilet",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 38 = urinal */
		0,
		alwaysTrue,
		 "Urinals",
		 "You have used the urinal",
		tags38,
		 libraryToilet,
		NULL,
		NULL,
		 "The urinals are stinky and stained",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 39 = supplyCloset */
		0,
		alwaysTrue,
		 "Supply Closet",
		 "The Supply Closet is locked",
		tags39,
		 libraryToilet,
		NULL,
		NULL,
		 "The Supply Closet is locked",
		"You see",
		 "You see the supply closet on this side of the toilet",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 40 = urinalCabin_1 */
		0,
		alwaysTrue,
		 "Urinal Cabin 1",
		"That is something that can not be used\n",
		tags40,
		 libraryToilet,
		NULL,
		NULL,
		 "The door is of blue color, it is locked from inside, it stinks very badly",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 41 = urinalCabin_2 */
		0,
		alwaysTrue,
		 "Urinal Cabin 2",
		"That is something that can not be used\n",
		tags41,
		 libraryToilet,
		NULL,
		NULL,
		 "The door is of blue color, it is locked from inside, it stinks very badly",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 42 = urinalCabin_3_entrance */
		0,
		alwaysTrue,
		 "Urinal Cabin 3",
		"That is something that can not be used\n",
		tags42,
		 libraryToilet,
		 urinalCabin_3,
		 urinalCabin_3,
		 "The door is of blue color, it is open , it stinks very badly, there is a wierd glow eminating from the cabin,there also seems to be a mysterious object on the floor of the cabin",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 43 = urinalCabin_3 */
		0,
		alwaysTrue,
		 "Urinal Cabin 3",
		"That is something that can not be used\n",
		tags43,
		NULL,
		NULL,
		NULL,
		 "The door is of blue color, it is open , it stinks very badly, there is a wierd glow eminating from the cabin,there also seems to be a mysterious object on the floor of the cabin",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 44 = urinalCabin_4 */
		0,
		alwaysTrue,
		 "Urinal Cabin 4",
		"That is something that can not be used\n",
		tags44,
		 libraryToilet,
		NULL,
		NULL,
		 "The door is of blue color, it is locked from inside, it stinks very badly",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 45 = libraryToiletExit */
		0,
		alwaysTrue,
		 "Exit of the toilet",
		"That is something that can not be used\n",
		tags45,
		 libraryToilet,
		 libraryShelf,
		 libraryShelf,
		"You see nothing special.\n",
		"You see",
		 "you have entered the book shelved",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 46 = mysteryObject */
		0,
		alwaysTrue,
		 "Body of a guard in mysterious uniform",
		"That is something that can not be used\n",
		tags46,
		 urinalCabin_3,
		NULL,
		NULL,
		 "The guard appears to be dead. His uniform is slightly burnt and doesnt appear to normal guard uniform",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 47 = portal */
		0,
		alwaysTrue,
		 "A portal type thing emanating green radiation",
		"That is something that can not be used\n",
		tags47,
		 urinalCabin_3,
		 alt_toilet,
		 alt_toilet,
		 "The portal is making very ominous sounds. You cant see through it. You can go through it......maybe",
		"You see",
		 "Where am I what is happening ? Where is the guard ? Where did the portal go ? Woah that was some strong acid yesterday",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 48 = alt_toilet */
		0,
		alwaysTrue,
		 "The library toilet",
		"That is something that can not be used\n",
		tags48,
		NULL,
		NULL,
		NULL,
		 "This toilet looks eerily similar to the one you were in but there is some ominous feeling about it",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 49 = alt_libraryToilet */
		0,
		alwaysTrue,
		 "The library toilet",
		"That is something that can not be used\n",
		tags49,
		NULL,
		NULL,
		NULL,
		 "It's dirty and has some weird mass lying around urinal cabin 3. It is glowing with some wierd glow",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 50 = alt_sink */
		0,
		alwaysTrue,
		 "Wash Basin",
		 "You have washed your hands and face",
		tags50,
		 alt_toilet,
		NULL,
		NULL,
		 "The tap in the wash basin is leaking slowly and there is no way to close it properly",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 51 = alt_urinal */
		0,
		alwaysTrue,
		 "Urinals",
		 "You have used the urinal",
		tags51,
		 alt_toilet,
		NULL,
		NULL,
		 "The urinals are stinky and stained",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 52 = alt_supplyCloset */
		0,
		alwaysTrue,
		 "Supply Closet",
		 "The Supply Closet is locked",
		tags52,
		 alt_toilet,
		NULL,
		NULL,
		 "The Supply Closet is locked",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 53 = alt_urinalCabin_1 */
		0,
		alwaysTrue,
		 "Urinal Cabin 1",
		"That is something that can not be used\n",
		tags53,
		 alt_toilet,
		NULL,
		NULL,
		 "The door is of blue color, it is locked from inside, it stinks very badly",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 54 = alt_urinalCabin_2 */
		0,
		alwaysTrue,
		 "Urinal Cabin 2",
		"That is something that can not be used\n",
		tags54,
		 alt_toilet,
		NULL,
		NULL,
		 "The door is of blue color, it is locked from inside, it stinks very badly",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 55 = alt_urinalCabin_3 */
		0,
		alwaysTrue,
		 "Urinal Cabin 3",
		"That is something that can not be used\n",
		tags55,
		 alt_toilet,
		NULL,
		NULL,
		 "The door is of blue color, it is open , it stinks very badly, there is a wierd glow eminating from the cabin,there also seems to be a mysterious object on the floor of the cabin",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 56 = alt_urinalCabin_4 */
		0,
		alwaysTrue,
		 "Urinal Cabin 4",
		"That is something that can not be used\n",
		tags56,
		 alt_toilet,
		NULL,
		NULL,
		 "The door is of blue color, it is locked from inside, it stinks very badly",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 57 = alt_ToiletExit */
		0,
		alwaysTrue,
		 "Exit of the toilet",
		"That is something that can not be used\n",
		tags57,
		 alt_toilet,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "This locked that is strange. Why not try opening the book it looks out of place",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 58 = alt_libraryShelf */
		0,
		alwaysTrue,
		 "The section with the book shelves",
		"That is something that can not be used\n",
		tags58,
		NULL,
		NULL,
		NULL,
		 "This is the reception of the library. This is your station you spend all your days here.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 59 = alt_shelf_1 */
		0,
		alwaysTrue,
		 "Book Shelf Number 1\n",
		"That is something that can not be used\n",
		tags59,
		 alt_libraryShelf,
		 alt_shelf_1,
		 alt_shelf_1,
		 "There are 2 books missing from this shelf.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 60 = alt_shelf_2 */
		0,
		alwaysTrue,
		 "Book Shelf Number 2\n",
		"That is something that can not be used\n",
		tags60,
		 alt_libraryShelf,
		 alt_shelf_2,
		 alt_shelf_2,
		 "There is 1 books missing from this shelf.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 61 = alt_shelf_3 */
		0,
		alwaysTrue,
		 "Book Shelf Number 3\n",
		"That is something that can not be used\n",
		tags61,
		 alt_libraryShelf,
		 alt_shelf_3,
		 alt_shelf_3,
		 "There are 2 books missing from this shelf.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 62 = alt_shelf_4 */
		0,
		alwaysTrue,
		 "Book Shelf Number 4\n",
		"That is something that can not be used\n",
		tags62,
		 alt_libraryShelf,
		 alt_shelf_4,
		 alt_shelf_4,
		 "There are 2 books missing from this shelf.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 63 = alt_shelf_1_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags63,
		 alt_shelf_1,
		 alt_libraryShelf,
		 alt_libraryShelf,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 64 = alt_shelf_2_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags64,
		 alt_shelf_2,
		 alt_libraryShelf,
		 alt_libraryShelf,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 65 = alt_shelf_3_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags65,
		 alt_shelf_3,
		 alt_libraryShelf,
		 alt_libraryShelf,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 66 = alt_shelf_4_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags66,
		 alt_shelf_4,
		 alt_libraryShelf,
		 alt_libraryShelf,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 67 = alt_shelf_1_toilet */
		0,
		alwaysTrue,
		 "Entrance of the toilet",
		"That is something that can not be used\n",
		tags67,
		 alt_shelf_1,
		 alt_libraryToilet,
		 alt_libraryToilet,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 68 = alt_shelf_2_toilet */
		0,
		alwaysTrue,
		 "Entrance of the toilet",
		"That is something that can not be used\n",
		tags68,
		 alt_shelf_2,
		 alt_libraryToilet,
		 alt_libraryToilet,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 69 = alt_shelf_3_toilet */
		0,
		alwaysTrue,
		 "Entrance of the toilet",
		"That is something that can not be used\n",
		tags69,
		 alt_shelf_3,
		 alt_libraryToilet,
		 alt_libraryToilet,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 70 = alt_shelf_4_toilet */
		0,
		alwaysTrue,
		 "Entrance of the toilet",
		"That is something that can not be used\n",
		tags70,
		 alt_shelf_4,
		 alt_libraryToilet,
		 alt_libraryToilet,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 71 = alt_shelf_toilet */
		0,
		alwaysTrue,
		 "Entrance of the toilet",
		"That is something that can not be used\n",
		tags71,
		 alt_libraryShelf,
		 alt_libraryToilet,
		 alt_libraryToilet,
		 "This is the exit of this shelf. Exit to explore the other shelves",
		"You see",
		 "You have entred the bathroom. There is some wierd light coming from cabin 3. There is also something on the floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 72 = level_1 */
		0,
		alwaysTrue,
		 "A book on the floor",
		"That is something that can not be used\n",
		tags72,
		 alt_toilet,
		 spawnlocation,
		 spawnlocation,
		 "It is a sherlock holmes book but why is it glowing",
		"You see",
		 "What is this what apartment is this",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 73 = levelExit_1 */
		0,
		alwaysTrue,
		 "Exit of the level PLACEHOLDER",
		"That is something that can not be used\n",
		tags73,
		 livinghall,
		 alt_libraryToilet,
		 alt_libraryToilet,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 74 = spawnlocation */
		0,
		alwaysTrue,
		 "an unknown location",
		"That is something that can not be used\n",
		tags74,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are in an unknown location where the surrounding is similar to Victoria England.\nYou see an apartment right in front of you.\nThere is also card on the ground.Perhaps you should 'examine' the card.",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 75 = intobasement */
		0,
		alwaysTrue,
		 "An unknown apartment",
		"That is something that can not be used\n",
		tags75,
		 spawnlocation,
		 basement,
		 basement,
		"You see nothing special.\n",
		"You see",
		 "You are in 221B Baker Street where Sherlock Holmes lives.\nYou are currently in the basement of the Apartment.\nYou see stairs that leads to his Room.",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 76 = card */
		0,
		alwaysTrue,
		 "Card lying on the ground",
		"That is something that can not be used\n",
		tags76,
		 spawnlocation,
		NULL,
		NULL,
		 "The card reads 'Save and you shall leave'.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 77 = basement */
		0,
		alwaysTrue,
		 "221 B Baker Street Aparatment Basement",
		"That is something that can not be used\n",
		tags77,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 78 = exit_apartment */
		0,
		alwaysTrue,
		 "The exit",
		"That is something that can not be used\n",
		tags78,
		 basement,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "The door is locked.You can't go outside.Moreover, nothing is visible outside.\nLike a void.",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 79 = upstairs */
		0,
		alwaysTrue,
		 "stairs that lead to Sherlocks' Room",
		"That is something that can not be used\n",
		tags79,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 80 = upstairs_entrance */
		0,
		alwaysTrue,
		 "Stairs leading to Sherlocks' Room",
		"That is something that can not be used\n",
		tags80,
		 basement,
		 upstairs,
		 upstairs,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 81 = upstairs_exit */
		0,
		alwaysTrue,
		 "Stairs leading to the basement",
		"That is something that can not be used\n",
		tags81,
		 upstairs,
		 basement,
		 basement,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 82 = livinghall */
		0,
		alwaysTrue,
		 "The Living Room",
		"That is something that can not be used\n",
		tags82,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 83 = livinghall_entrance */
		0,
		alwaysTrue,
		 "The living room",
		"That is something that can not be used\n",
		tags83,
		 upstairs,
		 livinghall,
		 livinghall,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 84 = livinghall_exit */
		0,
		alwaysTrue,
		 "The Stairs",
		"That is something that can not be used\n",
		tags84,
		 livinghall,
		 upstairs,
		 upstairs,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 85 = bedroomSherlock */
		0,
		alwaysTrue,
		 "The Bedroom",
		"That is something that can not be used\n",
		tags85,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 86 = bedroom_entranceSherlock */
		0,
		alwaysTrue,
		 "The bedroom",
		"That is something that can not be used\n",
		tags86,
		 livinghall,
		 bedroomSherlock,
		 bedroomSherlock,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 87 = bedroom_exitSherlock */
		0,
		alwaysTrue,
		 "The Living Room",
		"That is something that can not be used\n",
		tags87,
		 bedroomSherlock,
		 livinghall,
		 livinghall,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 88 = experimenttable */
		0,
		alwaysTrue,
		 "the Table where Sherlock Holmes does his experiment",
		"That is something that can not be used\n",
		tags88,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 89 = experimenttable_entrance */
		0,
		alwaysTrue,
		 "Experiment Table",
		"That is something that can not be used\n",
		tags89,
		 livinghall,
		 experimenttable,
		 experimenttable,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 90 = experimenttable_exit */
		0,
		alwaysTrue,
		 "The Living Room",
		"That is something that can not be used\n",
		tags90,
		 experimenttable,
		 livinghall,
		 livinghall,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 91 = diningtable */
		0,
		alwaysTrue,
		 "the Dining Table",
		"That is something that can not be used\n",
		tags91,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 92 = diningtable_entrance */
		0,
		alwaysTrue,
		 "Dining Table",
		"That is something that can not be used\n",
		tags92,
		 livinghall,
		 diningtable,
		 diningtable,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 93 = diningtable_exit */
		0,
		alwaysTrue,
		 "The Living Room",
		"That is something that can not be used\n",
		tags93,
		 diningtable,
		 livinghall,
		 livinghall,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 94 = alt_sink_level_exit */
		0,
		alwaysTrue,
		 "Wash Basin",
		 "You have washed your hands and face",
		tags94,
		 alt_libraryToilet,
		NULL,
		NULL,
		 "The tap in the wash basin is leaking slowly and there is no way to close it properly",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 95 = alt_urinal_level_exit */
		0,
		alwaysTrue,
		 "Urinals",
		 "You have used the urinal",
		tags95,
		 alt_libraryToilet,
		NULL,
		NULL,
		 "The urinals are stinky and stained",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 96 = alt_supplyCloset_level_exit */
		0,
		alwaysTrue,
		 "Supply Closet",
		 "The Supply Closet is locked",
		tags96,
		 alt_libraryToilet,
		NULL,
		NULL,
		 "The Supply Closet is locked",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 97 = alt_urinalCabin_1_level_exit */
		0,
		alwaysTrue,
		 "Urinal Cabin 1",
		"That is something that can not be used\n",
		tags97,
		 alt_libraryToilet,
		NULL,
		NULL,
		 "The door is of blue color, it is locked from inside, it stinks very badly",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 98 = alt_urinalCabin_2_level_exit */
		0,
		alwaysTrue,
		 "Urinal Cabin 2",
		"That is something that can not be used\n",
		tags98,
		 alt_libraryToilet,
		NULL,
		NULL,
		 "The door is of blue color, it is locked from inside, it stinks very badly",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 99 = alt_urinalCabin_3_level_exit */
		0,
		alwaysTrue,
		 "Urinal Cabin 3",
		"That is something that can not be used\n",
		tags99,
		 alt_libraryToilet,
		NULL,
		NULL,
		 "The door is of blue color, it is open , it stinks very badly, there is a wierd glow eminating from the cabin,there also seems to be a mysterious object on the floor of the cabin",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 100 = alt_urinalCabin_4_level_exit */
		0,
		alwaysTrue,
		 "Urinal Cabin 4",
		"That is something that can not be used\n",
		tags100,
		 alt_libraryToilet,
		NULL,
		NULL,
		 "The door is of blue color, it is locked from inside, it stinks very badly",
		"You see",
		 "The door is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 101 = alt_ToiletExit_locked */
		0,
		alwaysTrue,
		 "Exit of the toilet",
		"That is something that can not be used\n",
		tags101,
		 alt_libraryToilet,
		 alt_libraryShelf,
		 alt_libraryShelf,
		"You see nothing special.\n",
		"You see",
		 "This locked that is strange. Why not try opening the book it looks out of place",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 102 = alt_library */
		0,
		alwaysTrue,
		 "an old dusty library",
		"That is something that can not be used\n",
		tags102,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You have entred the library",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 103 = alt_libraryExit */
		0,
		alwaysTrue,
		 "Exit of the library",
		"That is something that can not be used\n",
		tags103,
		 alt_library,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "It is locked",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 104 = alt_libraryReception */
		0,
		alwaysTrue,
		 "The library reception",
		"That is something that can not be used\n",
		tags104,
		 alt_library,
		NULL,
		NULL,
		 "This is the reception of the library. This is your station you spend all your days here.",
		"You see",
		 "You are facing the reception",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 105 = alt_libraryShelfEntrance */
		0,
		alwaysTrue,
		 "The gorund floor book shelves",
		"That is something that can not be used\n",
		tags105,
		 alt_library,
		 alt_libraryShelf,
		 alt_libraryShelf,
		 "This is the reception of the library. This is your station you spend all your days here.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 106 = alt_libraryShelfExit */
		0,
		alwaysTrue,
		 "The library hall",
		"That is something that can not be used\n",
		tags106,
		 alt_libraryShelf,
		 alt_library,
		 alt_library,
		 "This is the reception of the library. This is your station you spend all your days here.",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 107 = stairs_floor_2 */
		0,
		alwaysTrue,
		 "The second floor stairs",
		"That is something that can not be used\n",
		tags107,
		 alt_library,
		 secondFloor,
		 secondFloor,
		"You see nothing special.\n",
		"You see",
		 "What these stairs were never here my library only had 1 floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 108 = firstFloor */
		0,
		alwaysTrue,
		 "The first floor stairs",
		"That is something that can not be used\n",
		tags108,
		 secondFloor,
		 alt_library,
		 alt_library,
		"You see nothing special.\n",
		"You see",
		 "The first floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 109 = secondFloor */
		0,
		alwaysTrue,
		 "The second floor",
		"That is something that can not be used\n",
		tags109,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 110 = secondFloorShelf */
		0,
		alwaysTrue,
		 "Second Floor book shelves",
		"That is something that can not be used\n",
		tags110,
		 secondFloor,
		 secondFloorShelf,
		 secondFloorShelf,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 111 = secondFloorShelf_1 */
		0,
		alwaysTrue,
		 "Book Shelf 1",
		"That is something that can not be used\n",
		tags111,
		 secondFloorShelf,
		 secondFloorShelf_1,
		 secondFloorShelf_1,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 112 = secondFloorShelf_2 */
		0,
		alwaysTrue,
		 "Book Shelf 2",
		"That is something that can not be used\n",
		tags112,
		 secondFloorShelf,
		 secondFloorShelf_2,
		 secondFloorShelf_2,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 113 = secondFloorShelf_3 */
		0,
		alwaysTrue,
		 "Book Shelf 3",
		"That is something that can not be used\n",
		tags113,
		 secondFloorShelf,
		 secondFloorShelf_3,
		 secondFloorShelf_3,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 114 = secondFloorShelf_4 */
		0,
		alwaysTrue,
		 "Book Shelf 4",
		"That is something that can not be used\n",
		tags114,
		 secondFloorShelf,
		 secondFloorShelf_4,
		 secondFloorShelf_4,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 115 = secondFloorShelf_hall */
		0,
		alwaysTrue,
		 "Second floor Hall",
		"That is something that can not be used\n",
		tags115,
		 secondFloorShelf,
		 secondFloor,
		 secondFloor,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 116 = secondFloorShelf_1_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags116,
		 secondFloorShelf_1,
		 secondFloorShelf,
		 secondFloorShelf,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 117 = secondFloorShelf_2_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags117,
		 secondFloorShelf_2,
		 secondFloorShelf,
		 secondFloorShelf,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 118 = secondFloorShelf_3_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags118,
		 secondFloorShelf_3,
		 secondFloorShelf,
		 secondFloorShelf,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 119 = secondFloorShelf_4_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags119,
		 secondFloorShelf_4,
		 secondFloorShelf,
		 secondFloorShelf,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 120 = computerCorner */
		0,
		alwaysTrue,
		 "Computer area for research",
		 "The power is down try again later",
		tags120,
		 secondFloor,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are in front of a computer",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 121 = level_2 */
		0,
		alwaysTrue,
		 "A mysterious book",
		"That is something that can not be used\n",
		tags121,
		 secondFloorShelf_3,
		 lakshagriha,
		 lakshagriha,
		"You see nothing special.\n",
		"You see",
		 "What is this PLACEHOLDER",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 122 = lakshagriha */
		0,
		alwaysTrue,
		 "place with the burning castle",
		"That is something that can not be used\n",
		tags122,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are in the city of lakshagriha\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 123 = lakshagrihaEntrance */
		0,
		alwaysTrue,
		 "Entrance of the lakshagriha area",
		"That is something that can not be used\n",
		tags123,
		 lakshagriha,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You entred the lakshagriha area\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 124 = lakshagrihacastle */
		0,
		alwaysTrue,
		 "lakshagrihacastle\n",
		"That is something that can not be used\n",
		tags124,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You entred the lakshagrihacastle\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 125 = lakshagrihacastleEntrance */
		0,
		alwaysTrue,
		 "Entrance of the lakshagrihacastle",
		"That is something that can not be used\n",
		tags125,
		 lakshagriha,
		 lakshagrihacastle,
		 lakshagrihacastle,
		"You see nothing special.\n",
		"You see",
		 "You entred the lakshagriha Castle\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 126 = lakshagrihacastleWalls */
		0,
		alwaysTrue,
		 "lakshagrihacastle walls",
		"That is something that can not be used\n",
		tags126,
		 lakshagrihacastle,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "There is nothing but walls there\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 127 = lakshagrihacastleExit */
		0,
		alwaysTrue,
		 "Exit of the lakshagrihacastle",
		"That is something that can not be used\n",
		tags127,
		 lakshagrihacastle,
		 roadMahabharat,
		 roadMahabharat,
		"You see nothing special.\n",
		"You see",
		 "You are on the road towards village\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 128 = roadMahabharat */
		0,
		alwaysTrue,
		 "the road leads to the village",
		"That is something that can not be used\n",
		tags128,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are on the road that leads you to the village",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 129 = roadentranceMahabharat */
		0,
		alwaysTrue,
		 "The Road leads to the Village",
		"That is something that can not be used\n",
		tags129,
		 lakshagriha,
		 roadMahabharat,
		 roadMahabharat,
		"You see nothing special.\n",
		"You see",
		 "You are on the road that leads to the Village\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 130 = roadWallsMahabharat */
		0,
		alwaysTrue,
		 "only jungle",
		"That is something that can not be used\n",
		tags130,
		 roadMahabharat,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "There is nothing but jungle all around and a narrow road that leads to small village\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 131 = roadexit */
		0,
		alwaysTrue,
		 "The exit ",
		"That is something that can not be used\n",
		tags131,
		 roadMahabharat,
		 lakshagriha,
		 lakshagriha,
		"You see nothing special.\n",
		"You see",
		 "You are on the road that leads to the Village\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 132 = village */
		0,
		alwaysTrue,
		 "an old small village",
		"That is something that can not be used\n",
		tags132,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are here so that you can understand the language speak by the people of the Village and hide from the Fireman so that he couldn't kill you......\n You are in the front of the village\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 133 = villageEntrance */
		0,
		alwaysTrue,
		 "entrance to the village",
		"That is something that can not be used\n",
		tags133,
		 roadMahabharat,
		 village,
		 village,
		"You see nothing special.\n",
		"You see",
		 "You entred the village\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 134 = villageWalls */
		0,
		alwaysTrue,
		 "surrounded by mountains",
		"That is something that can not be used\n",
		tags134,
		 village,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "Whole village is surronded by the mountains and the jungle\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 135 = villagexit */
		0,
		alwaysTrue,
		 "exit to the village",
		"That is something that can not be used\n",
		tags135,
		 village,
		 road1Mahabharat,
		 road1Mahabharat,
		"You see nothing special.\n",
		"You see",
		 "You have exited the village and move towards the Hatinapur castle where pandavas appeared after long time and demand for their own Kingdom\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 136 = road1Mahabharat */
		0,
		alwaysTrue,
		 "the road leads to the Hastinapur Castle\n",
		"That is something that can not be used\n",
		tags136,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are on the road that leads you to the village",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 137 = road1entrance */
		0,
		alwaysTrue,
		 "The Road leads to the Hatinapur Castle\n",
		"That is something that can not be used\n",
		tags137,
		 road1Mahabharat,
		 hastinapurcastle,
		 hastinapurcastle,
		"You see nothing special.\n",
		"You see",
		 "You are on the road that leads to the Hastinapur Castle\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 138 = road1WallsMahabharat */
		0,
		alwaysTrue,
		 "only jungle",
		"That is something that can not be used\n",
		tags138,
		 road1Mahabharat,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "There is nothing but jungle all around and a narrow road that leads to Hastinapur Castle\n ",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 139 = road1exitMahabharat */
		0,
		alwaysTrue,
		 "back to village",
		"That is something that can not be used\n",
		tags139,
		 road1Mahabharat,
		 village,
		 village,
		"You see nothing special.\n",
		"You see",
		 "back to village\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 140 = hastinapurcastle */
		0,
		alwaysTrue,
		 "Welcome to the castle",
		"That is something that can not be used\n",
		tags140,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are at the glorious castle",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 141 = hastinapurcastlgate */
		0,
		alwaysTrue,
		 "You were at the gate of the Castle\n",
		"That is something that can not be used\n",
		tags141,
		 hastinapurcastle,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You were at the Gate for Entering the Castle\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 142 = hastinapurcastleentrance */
		0,
		alwaysTrue,
		 "Entered to the Castle\n",
		"That is something that can not be used\n",
		tags142,
		 hastinapurcastle,
		 meetinghall,
		 meetinghall,
		"You see nothing special.\n",
		"You see",
		 "Entered to the Castle Hastinapur Castle and Headed towards the Meeting hall\n ",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 143 = meetinghall */
		0,
		alwaysTrue,
		 "Meeting Hall\n",
		"That is something that can not be used\n",
		tags143,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "It's a Place where the game of Politics begins\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 144 = meetinghallentrance */
		0,
		alwaysTrue,
		 "Entrance",
		"That is something that can not be used\n",
		tags144,
		 meetinghall,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "At the Entrance of the Meeting Hall\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		 99999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 145 = levelExit_2 */
		0,
		alwaysTrue,
		 "Level Exit PLACEHOLDER",
		"That is something that can not be used\n",
		tags145,
		 meetinghall,
		 secondFloorShelf_3_alt,
		 secondFloorShelf_3_alt,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 146 = secondFloor_alt */
		0,
		alwaysTrue,
		 "The second floor",
		"That is something that can not be used\n",
		tags146,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 147 = secondFloorShelf_alt */
		0,
		alwaysTrue,
		 "Second Floor book shelves",
		"That is something that can not be used\n",
		tags147,
		 secondFloor_alt,
		 secondFloorShelf_alt,
		 secondFloorShelf_alt,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 148 = secondFloorShelf_1_alt */
		0,
		alwaysTrue,
		 "Book Shelf 1",
		"That is something that can not be used\n",
		tags148,
		 secondFloorShelf_alt,
		 secondFloorShelf_1_alt,
		 secondFloorShelf_1_alt,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 149 = secondFloorShelf_2_alt */
		0,
		alwaysTrue,
		 "Book Shelf 2",
		"That is something that can not be used\n",
		tags149,
		 secondFloorShelf_alt,
		 secondFloorShelf_2_alt,
		 secondFloorShelf_2_alt,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 150 = secondFloorShelf_3_alt */
		0,
		alwaysTrue,
		 "Book Shelf 3",
		"That is something that can not be used\n",
		tags150,
		 secondFloorShelf_alt,
		 secondFloorShelf_3_alt,
		 secondFloorShelf_3_alt,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 151 = secondFloorShelf_4_alt */
		0,
		alwaysTrue,
		 "Book Shelf 4",
		"That is something that can not be used\n",
		tags151,
		 secondFloorShelf_alt,
		 secondFloorShelf_4_alt,
		 secondFloorShelf_4_alt,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 152 = secondFloorShelf_hall_alt */
		0,
		alwaysTrue,
		 "Second floor Hall",
		"That is something that can not be used\n",
		tags152,
		 secondFloorShelf_alt,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "GO FORWARD EVERYTHING IS ON FIRE HERE",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 153 = secondFloorShelf_1_exit_alt */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags153,
		 secondFloorShelf_1_alt,
		 secondFloorShelf_alt,
		 secondFloorShelf_alt,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 154 = secondFloorShelf_2_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags154,
		 secondFloorShelf_2_alt,
		 secondFloorShelf_alt,
		 secondFloorShelf_alt,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 155 = secondFloorShelf_3_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags155,
		 secondFloorShelf_3_alt,
		 secondFloorShelf_alt,
		 secondFloorShelf_alt,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 156 = secondFloorShelf_4_exit */
		0,
		alwaysTrue,
		 "Exit of the shelf",
		"That is something that can not be used\n",
		tags156,
		 secondFloorShelf_4_alt,
		 secondFloorShelf_alt,
		 secondFloorShelf_alt,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 157 = stairs_floor_3_1 */
		0,
		alwaysTrue,
		 "The third floor stairs",
		"That is something that can not be used\n",
		tags157,
		 secondFloorShelf_alt,
		 thirdFloor,
		 thirdFloor,
		"You see nothing special.\n",
		"You see",
		 "What these stairs were never here my library only had 1 floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 158 = stairs_floor_3_1 */
		0,
		alwaysTrue,
		 "The third floor stairs",
		"That is something that can not be used\n",
		tags158,
		 secondFloorShelf_1_alt,
		 thirdFloor,
		 thirdFloor,
		"You see nothing special.\n",
		"You see",
		 "What these stairs were never here my library only had 1 floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 159 = stairs_floor_3_2 */
		0,
		alwaysTrue,
		 "The third floor stairs",
		"That is something that can not be used\n",
		tags159,
		 secondFloorShelf_2_alt,
		 thirdFloor,
		 thirdFloor,
		"You see nothing special.\n",
		"You see",
		 "What these stairs were never here my library only had 1 floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 160 = stairs_floor_3_3 */
		0,
		alwaysTrue,
		 "The third floor stairs",
		"That is something that can not be used\n",
		tags160,
		 secondFloorShelf_3_alt,
		 thirdFloor,
		 thirdFloor,
		"You see nothing special.\n",
		"You see",
		 "What these stairs were never here my library only had 1 floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 161 = stairs_floor_3_4 */
		0,
		alwaysTrue,
		 "The third floor stairs",
		"That is something that can not be used\n",
		tags161,
		 secondFloorShelf_4_alt,
		 thirdFloor,
		 thirdFloor,
		"You see nothing special.\n",
		"You see",
		 "What these stairs were never here my library only had 1 floor",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 162 = thirdFloor */
		0,
		alwaysTrue,
		 "the third floor reading room",
		"That is something that can not be used\n",
		tags162,
		NULL,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 163 = stairsSecondFloorDown */
		0,
		alwaysTrue,
		 "Stairs to the second floor",
		"That is something that can not be used\n",
		tags163,
		 thirdFloor,
		 secondFloorShelf_alt,
		 secondFloorShelf_alt,
		"You see nothing special.\n",
		"You see",
		 "You went down the stairs to the shelf",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 164 = table_1 */
		0,
		alwaysTrue,
		 "Reading room table 1",
		"That is something that can not be used\n",
		tags164,
		 thirdFloor,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are facing table 1",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 165 = table_2 */
		0,
		alwaysTrue,
		 "Reading room table 2",
		"That is something that can not be used\n",
		tags165,
		 thirdFloor,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are facing table 2",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 166 = table_3 */
		0,
		alwaysTrue,
		 "Reading room table 3",
		"That is something that can not be used\n",
		tags166,
		 thirdFloor,
		NULL,
		NULL,
		"You see nothing special.\n",
		"You see",
		 "You are facing table 3",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 167 = level_3 */
		0,
		alwaysTrue,
		 "A book on table 3",
		"That is something that can not be used\n",
		tags167,
		 thirdFloor,
		 porcelianPalace,
		 porcelianPalace,
		"You see nothing special.\n",
		"You see",
		 "What place is this why are there these paintings on the wall? What is it this time",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 168 = porcelianPalace */
		0,
		alwaysTrue,
		 "a mysterious alley",
		"That is something that can not be used\n",
		tags168,
		NULL,
		NULL,
		NULL,
		 "This looks like a mueseum of some sort there are paintings on the wall. Fossils all around and many things you don't recoganize",
		"You see",
		 "You cant get much closer than this",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 169 = distantVoice */
		0,
		alwaysTrue,
		 "you hear pepole talking from far east",
		"That is something that can not be used\n",
		tags169,
		 porcelianPalace,
		NULL,
		NULL,
		 "There seems to be 2 pepole talking ",
		"You see",
		 "That little child looks wierd I wonder what it is",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 170 = guard */
		0,
		alwaysTrue,
		 "a burly guard",
		"That is something that can not be used\n",
		tags170,
		 bedroom,
		NULL,
		NULL,
		 "You would need a mirror to look at yourself.\n",
		 "You have",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		 20,
		 100,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	},
	{	/* 171 = player */
		0,
		alwaysTrue,
		 "yourself",
		"That is something that can not be used\n",
		tags171,
		 bedroom,
		NULL,
		NULL,
		 "You would need a mirror to look at yourself.\n",
		 "You have",
		"You can't get much closer than this.\n",
		"I dont know anything about it.\n",
		"Level 1\n",
		"Level 2\n",
		"I dont know anything about it.\n",
		99,
		 20,
		 100,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked
	}
};
