#include <stdbool.h>

typedef struct object {
    int           level;
    bool         (*condition)(void);
    const char* description;
    const char* usage;
    const char** tags;
    struct object* location;
    struct object* destination;
    struct object* prospect;
    const char* details;
    const char* contents;
    const char* textGo;
    const char* gossip;
    const char* gossip_1;
    const char* gossip_2;
    const char* gossip_3;
    int            weight;
    int            capacity;
    int            health;
    const char* (*open)(void);
    const char* (*close)(void);
    const char* (*lock)(void);
    const char* (*unlock)(void);
} OBJECT;


extern OBJECT objs[];
//bathroom
#define bathroom	(objs + 0)
#define bathroomWallToilet	(objs + 1)
#define bedroomEntrance	(objs + 2)
#define toilet	(objs + 3)
#define shower	(objs + 4)
#define toothbrush	(objs + 5)
#define bedroom	(objs + 6)
#define openDoorToBackroom	(objs + 7)
#define closedDoorToBackroom	(objs + 8)
#define bedroomWalls	(objs + 9)
#define bedroomExit	(objs + 10)
#define backpack	(objs + 11)
#define libraryKeys	(objs + 12)
#define secretBook	(objs + 13)
#define roadLibrary	(objs + 14)
#define roadWalls	(objs + 15)
#define openDoorToLibrary	(objs + 16)
#define closedDoorToLibrary	(objs + 17)
#define lockedDoorToLibrary	(objs + 18)
#define library	(objs + 19)
#define libraryExit	(objs + 20)
#define libraryReception	(objs + 21)
#define libraryShelfEntrance	(objs + 22)
#define libraryShelf	(objs + 23)
#define shelf_1	(objs + 24)
#define shelf_2	(objs + 25)
#define shelf_3	(objs + 26)
#define shelf_4	(objs + 27)
#define shelf_1_exit	(objs + 28)
#define shelf_2_exit	(objs + 29)
#define shelf_3_exit	(objs + 30)
#define shelf_4_exit	(objs + 31)
#define shelf_1_toilet	(objs + 32)
#define shelf_2_toilet	(objs + 33)
#define shelf_3_toilet	(objs + 34)
#define shelf_4_toilet	(objs + 35)
#define shelf_toilet	(objs + 36)
#define libraryToilet	(objs + 37)
#define sink	(objs + 38)
#define urinal	(objs + 39)
#define supplyCloset	(objs + 40)
#define urinalCabin_1	(objs + 41)
#define urinalCabin_2	(objs + 42)
#define urinalCabin_3_entrance	(objs + 43)
#define urinalCabin_3	(objs + 44)
#define urinalCabin_4	(objs + 45)
#define libraryToiletExit	(objs + 46)
#define mysteryObject	(objs + 47)
#define portal	(objs + 48)
#define alt_toilet	(objs + 49)
#define alt_libraryToilet	(objs + 50)
#define alt_sink	(objs + 51)
#define alt_urinal	(objs + 52)
#define alt_supplyCloset	(objs + 53)
#define alt_urinalCabin_1	(objs + 54)
#define alt_urinalCabin_2	(objs + 55)
#define alt_urinalCabin_3	(objs + 56)
#define alt_urinalCabin_4	(objs + 57)
#define alt_ToiletExit	(objs + 58)
#define alt_libraryShelf	(objs + 59)
#define alt_shelf_1	(objs + 60)
#define alt_shelf_2	(objs + 61)
#define alt_shelf_3	(objs + 62)
#define alt_shelf_4	(objs + 63)
#define alt_shelf_1_exit	(objs + 64)
#define alt_shelf_2_exit	(objs + 65)
#define alt_shelf_3_exit	(objs + 66)
#define alt_shelf_4_exit	(objs + 67)
#define alt_shelf_1_toilet	(objs + 68)
#define alt_shelf_2_toilet	(objs + 69)
#define alt_shelf_3_toilet	(objs + 70)
#define alt_shelf_4_toilet	(objs + 71)
#define alt_shelf_toilet	(objs + 72)
#define level_1	(objs + 73)
#define openDoorToSherlock	(objs + 74)
#define closedDoorToSherlock	(objs + 75)
#define lockedDoorToSherlock	(objs + 76)
#define spawnlocation	(objs + 77)
#define intobasement	(objs + 78)
#define card	(objs + 79)
#define basement	(objs + 80)
#define riddle_1	(objs + 81)
#define upstairs	(objs + 82)
#define exit_apartment	(objs + 83)
#define upstairs_entrance	(objs + 84)
#define upstairs_exit	(objs + 85)
#define livinghall	(objs + 86)
#define livinghall_entrance	(objs + 87)
#define livinghall_exit	(objs + 88)
#define riddle_2	(objs + 89)
#define bedroomSherlock	(objs + 90)
#define bedroom_entranceSherlock	(objs + 91)
#define bedroom_exitSherlock	(objs + 92)
#define experimenttable	(objs + 93)
#define riddle_3	(objs + 94)
#define openBoxWood	(objs + 95)
#define closedBoxWood	(objs + 96)
#define openBoxMetal	(objs + 97)
#define closedBoxMetal	(objs + 98)
#define openBoxGlass	(objs + 99)
#define closedBoxGlass	(objs + 100)
#define openBoxGold	(objs + 101)
#define closedBoxGold	(objs + 102)
#define sherlockKey	(objs + 103)
#define experimenttable_entrance	(objs + 104)
#define experimenttable_exit	(objs + 105)
#define diningtable	(objs + 106)
#define diningtable_entrance	(objs + 107)
#define diningtable_exit	(objs + 108)
#define alt_sink_level_exit	(objs + 109)
#define alt_urinal_level_exit	(objs + 110)
#define alt_supplyCloset_level_exit	(objs + 111)
#define alt_urinalCabin_1_level_exit	(objs + 112)
#define alt_urinalCabin_2_level_exit	(objs + 113)
#define alt_urinalCabin_3_level_exit	(objs + 114)
#define alt_urinalCabin_4_level_exit	(objs + 115)
#define alt_ToiletExit_locked	(objs + 116)
#define alt_library	(objs + 117)
#define alt_libraryExit	(objs + 118)
#define alt_libraryReception	(objs + 119)
#define alt_libraryShelfEntrance	(objs + 120)
#define alt_libraryShelfExit	(objs + 121)
#define stairs_floor_2	(objs + 122)
#define firstFloor	(objs + 123)
#define secondFloor	(objs + 124)
#define secondFloorShelf	(objs + 125)
#define secondFloorShelf_1	(objs + 126)
#define secondFloorShelf_2	(objs + 127)
#define secondFloorShelf_3	(objs + 128)
#define secondFloorShelf_4	(objs + 129)
#define secondFloorShelf_hall	(objs + 130)
#define secondFloorShelf_1_exit	(objs + 131)
#define secondFloorShelf_2_exit	(objs + 132)
#define secondFloorShelf_3_exit	(objs + 133)
#define secondFloorShelf_4_exit	(objs + 134)
#define computerCorner	(objs + 135)
#define level_2	(objs + 136)
#define lakshagriha	(objs + 137)
#define lakshagrihaEntrance	(objs + 138)
#define lakshagrihacastle	(objs + 139)
#define lakshagrihacastleEntrance	(objs + 140)
#define lakshagrihacastleWalls	(objs + 141)
#define lakshagrihacastleExit	(objs + 142)
#define roadMahabharat	(objs + 143)
#define roadentranceMahabharat	(objs + 144)
#define roadWallsMahabharat	(objs + 145)
#define roadexit	(objs + 146)
#define hastinapurcastle	(objs + 147)
#define hastinapurcastlgate	(objs + 148)
#define hastinapurcastleentrance	(objs + 149)
#define meetinghall	(objs + 150)
#define meetinghallentrance	(objs + 151)
#define tic	(objs + 152)
#define openDoorToSeclock	(objs + 153)
#define closedDoorToSeclock	(objs + 154)
#define lockedDoorToSeclock	(objs + 155)
#define secondFloor_alt	(objs + 156)
#define secondFloorShelf_alt	(objs + 157)
#define secondFloorShelf_1_alt	(objs + 158)
#define secondFloorShelf_2_alt	(objs + 159)
#define secondFloorShelf_3_alt	(objs + 160)
#define secondFloorShelf_4_alt	(objs + 161)
#define secondFloorShelf_hall_alt	(objs + 162)
#define secondFloorShelf_1_exit_alt	(objs + 163)
#define secondFloorShelf_2_exit	(objs + 164)
#define secondFloorShelf_3_exit	(objs + 165)
#define secondFloorShelf_4_exit	(objs + 166)
#define stairs_floor_3_1	(objs + 167)
#define stairs_floor_3_1	(objs + 168)
#define stairs_floor_3_2	(objs + 169)
#define stairs_floor_3_3	(objs + 170)
#define stairs_floor_3_4	(objs + 171)
#define thirdFloor	(objs + 172)
#define stairsSecondFloorDown	(objs + 173)
#define table_1	(objs + 174)
#define table_2	(objs + 175)
#define table_3	(objs + 176)
#define level_3	(objs + 177)
#define porcelianPalace	(objs + 178)
#define distantVoice	(objs + 179)
#define porcelianPalaceHall	(objs + 180)
#define child	(objs + 181)
#define stranger	(objs + 182)
#define mysterious_entrance	(objs + 183)
#define maize_1	(objs + 184)
#define maize_1_top	(objs + 185)
#define maize_1_left	(objs + 186)
#define maize_1_right	(objs + 187)
#define maize_1_bottom	(objs + 188)
#define maize_2	(objs + 189)
#define maize_2_top	(objs + 190)
#define maize_2_left	(objs + 191)
#define maize_2_right	(objs + 192)
#define maize_2_bottom	(objs + 193)
#define maize_3	(objs + 194)
#define maize_3_top	(objs + 195)
#define maize_3_left	(objs + 196)
#define maize_3_right	(objs + 197)
#define maize_3_bottom	(objs + 198)
#define maize_4	(objs + 199)
#define maize_4_top	(objs + 200)
#define maize_4_left	(objs + 201)
#define maize_4_right	(objs + 202)
#define maize_4_bottom	(objs + 203)
#define maize_5	(objs + 204)
#define maize_5_top	(objs + 205)
#define maize_5_left	(objs + 206)
#define maize_5_right	(objs + 207)
#define maize_5_bottom	(objs + 208)
#define maize_6	(objs + 209)
#define maize_6_top	(objs + 210)
#define maize_6_left	(objs + 211)
#define maize_6_right	(objs + 212)
#define maize_6_bottom	(objs + 213)
#define maize_7	(objs + 214)
#define maize_7_top	(objs + 215)
#define maize_7_left	(objs + 216)
#define maize_7_right	(objs + 217)
#define maize_7_bottom	(objs + 218)
#define maize_8	(objs + 219)
#define maize_8_top	(objs + 220)
#define maize_8_left	(objs + 221)
#define maize_8_right	(objs + 222)
#define maize_8_bottom	(objs + 223)
#define maize_exit_hall	(objs + 224)
#define weena	(objs + 225)
#define the_time_traveller	(objs + 226)
#define portal_level_3	(objs + 227)
#define thirdFloor_alt	(objs + 228)
#define stairsSecondFloorDown_alt	(objs + 229)
#define table_1_alt	(objs + 230)
#define table_2_alt	(objs + 231)
#define table_3_alt	(objs + 232)
#define roof_door	(objs + 233)
#define roof	(objs + 234)
#define book_4	(objs + 235)
#define guard	(objs + 236)
#define player	(objs + 237)

#define endOfObjs	(objs + 238)

#define validObject(obj)	((obj) != NULL && (*(obj)->condition)())

#define forEachObject(obj)	for (obj = objs; obj < endOfObjs; obj++) if (validObject(obj))
